# permissions for end users to edit secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: envoy-xds-controller
    app.kubernetes.io/managed-by: kustomize
  name: secret-editor-role
rules:
- apiGroups:
  - envoy.kaasops.io
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - envoy.kaasops.io
  resources:
  - secrets/status
  verbs:
  - get
