# permissions for end users to edit virtualservicetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtualservicetemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: envoy-xds-controller
    app.kubernetes.io/part-of: envoy-xds-controller
    app.kubernetes.io/managed-by: kustomize
  name: virtualservicetemplate-editor-role
rules:
- apiGroups:
  - envoy.kaasops.io
  resources:
  - virtualservicetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - envoy.kaasops.io
  resources:
  - virtualservicetemplates/status
  verbs:
  - get
