
{{- if .Values.webhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
{{- range .Values.webhook.webhooks }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: Cg==
      service:
        name: envoy-xds-controller-webhook-service
        namespace: {{ $.Release.Namespace }}
        path: {{ .clientConfig.service.path }}
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: {{ .name }}
    namespaceSelector: {}
    objectSelector: {}
    rules: {{ .rules | toYaml | nindent 4 }}
    sideEffects: None
    timeoutSeconds: 10
{{- end }}
{{- end -}}

