{{- if .Values.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  OIDC_ENABLED: "{{ .Values.auth.enabled | toJson | trim | b64enc }}"
  OIDC_CLIENT_ID: "{{ .Values.auth.oidc.clientId | b64enc }}"
  OIDC_ISSUER_URL: "{{ .Values.auth.oidc.issuerUrl | b64enc }}"
  OIDC_SCOPE: "{{ .Values.auth.oidc.scope | b64enc }}"
  OIDC_REDIRECT_URI: "{{ .Values.auth.oidc.redirectUri | b64enc }}"
{{- end }}