// /*
// Copyright 2023.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */

package v1alpha1

import (
	"context"
	"fmt"
	"strconv"

	accesslogv3 "github.com/envoyproxy/go-control-plane/envoy/config/accesslog/v3"
	filev3 "github.com/envoyproxy/go-control-plane/envoy/extensions/access_loggers/file/v3"

	"github.com/kaasops/envoy-xds-controller/pkg/errors"
	"github.com/kaasops/envoy-xds-controller/pkg/options"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func (alc *AccessLogConfig) Validate(ctx context.Context) error {
	// Validate AccessLogConfig spec
	if alc.Spec == nil {
		return errors.New(errors.AccessLogConfigCannotBeEmptyMessage)
	}

	accessLogConfigv3 := &accesslogv3.AccessLog{}
	if err := options.Unmarshaler.Unmarshal(alc.Spec.Raw, accessLogConfigv3); err != nil {
		return errors.Wrap(err, errors.UnmarshalMessage)
	}

	err := accessLogConfigv3.ValidateAll()
	if err != nil {
		return errors.Wrap(err, errors.ValidateStructMessage)
	}

	// Validate if file type set path
	configType, ok := accessLogConfigv3.GetConfigType().(*accesslogv3.AccessLog_TypedConfig)
	if !ok {
		return errors.New(errors.ConvertTypeErrorMessage)
	}
	fileConfig := &filev3.FileAccessLog{}
	if err := configType.TypedConfig.UnmarshalTo(fileConfig); err == nil {
		if fileConfig.Path == "" {
			return errors.New(errors.AccessLogConfigFileEmptyPath)
		}
	}

	// Validate annotations
	err = alc.validateAutoGenerateFilename(accessLogConfigv3)
	if err != nil {
		return err
	}

	return nil
}

func (alc *AccessLogConfig) validateAutoGenerateFilename(accessLogConfigv3 *accesslogv3.AccessLog) error {
	val, ok := alc.Annotations[options.AutoGeneratedFilename]
	if ok {
		val, err := strconv.ParseBool(val)
		if err != nil {
			return errors.New(errors.AccessLogAutoGeneratedFilenameBool)
		}

		if val {
			fileConfig := &filev3.FileAccessLog{}
			configType, ok := accessLogConfigv3.GetConfigType().(*accesslogv3.AccessLog_TypedConfig)
			if !ok {
				return errors.New(errors.AccessLogAutoGeneratedFilenameFileType)
			}

			if err := configType.TypedConfig.UnmarshalTo(fileConfig); err != nil {
				return errors.Wrap(err, errors.AccessLogAutoGeneratedFilenameFileType)
			}
		}
	}
	return nil
}

func (alc *AccessLogConfig) ValidateDelete(ctx context.Context, cl client.Client) error {
	virtualServices := &VirtualServiceList{}
	listOpts := []client.ListOption{client.InNamespace(alc.Namespace)}
	if err := cl.List(ctx, virtualServices, listOpts...); err != nil {
		return err
	}

	if len(virtualServices.Items) > 0 {
		vsNames := []string{}
		for _, vs := range virtualServices.Items {
			if vs.Spec.AccessLogConfig != nil {
				if vs.Spec.AccessLogConfig.Name == alc.Name {
					vsNames = append(vsNames, vs.Name)
					continue
				}
			}
		}
		if len(vsNames) > 0 {
			return errors.New(fmt.Sprintf("%v%+v", errors.AccessLogConfigDeleteUsedMessage, vsNames))
		}
	}

	virtualServiceTemplates := &VirtualServiceTemplateList{}
	vstListOpts := []client.ListOption{
		client.InNamespace(alc.Namespace),
		client.MatchingFields{options.VirtualServiceTemplateAccessLogConfigNameField: alc.Name},
	}
	if err := cl.List(ctx, virtualServiceTemplates, vstListOpts...); err != nil {
		return err
	}

	if len(virtualServiceTemplates.Items) > 0 {
		vstNames := make([]string, 0, len(virtualServiceTemplates.Items))
		for _, vs := range virtualServiceTemplates.Items {
			vstNames = append(vstNames, vs.Name)
		}
		return errors.New(fmt.Sprintf("%v: %+v", errors.AccessLogConfigUsedInVST, vstNames))
	}

	return nil
}
