{{- if .Values.acl.nodeIdsByGroup -}}
apiVersion: v1
kind: Secret
metadata:
  name: acl
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  ACL_CONFIG: {{ .Values.acl.nodeIdsByGroup | toJson | b64enc }}
{{- end }}