package options

import "google.golang.org/protobuf/encoding/protojson"

const (
	DefaultListenerName                            = "https"
	VirtualServiceListenerNameField                = "spec.listener.name"
	VirtualServiceTemplateListenerNameField        = "spec.listener.name"
	VirtualServiceTemplateAccessLogConfigNameField = "spec.accessLog.name"
	VirtualServiceTemplateNameField                = "spec.template.name"
	NodeIDAnnotation                               = "envoy.kaasops.io/node-id"
	SecretLabelKey                                 = "envoy.kaasops.io/secret-type"
	SdsSecretLabelValue                            = "sds-cached"
	WebhookSecretLabelValue                        = "webhook"

	AutoDiscoveryLabel = "envoy.kaasops.io/autoDiscovery"
	DomainAnnotation   = "envoy.kaasops.io/domains"

	// AutoGeneratedFilename is the annotation key for the auto-generated filename for access logs
	// Name for access logs = virtualservice name
	// Worked only for AccessLogConfig with file type
	// bolean value
	AutoGeneratedFilename = "envoy.kaasops.io/auto-generated-filename"
)

var (
	Unmarshaler = protojson.UnmarshalOptions{
		AllowPartial: false,
		// DiscardUnknown: true,
	}
)
