name: Tests
on:
  push:
    branches:
    - "main"
    tags:
      - 'v*'
  pull_request:
    branches:
    - "main"
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  conformance-test-1-29:
    runs-on: ubuntu-latest
    permissions:
      contents: read   #  for actions/checkout
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: ./tools/github-actions/setup-deps
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Run Conformance Tests for Kubenetes 1.29
      run: make conformance-1.29
  conformance-test-1-30:
    runs-on: ubuntu-latest
    permissions:
      contents: read   #  for actions/checkout
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: ./tools/github-actions/setup-deps
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Run Conformance Tests for Kubenetes 1.30
      run: make conformance-1.30
  e2e-test-1-29:
    runs-on: ubuntu-latest
    permissions:
      contents: read   #  for actions/checkout
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: ./tools/github-actions/setup-deps
    - name: Run E2e Tests on Kubernetes 1.29
      run: make e2e-1.29
  e2e-test-1-30:
    runs-on: ubuntu-latest
    permissions:
      contents: read   #  for actions/checkout
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: ./tools/github-actions/setup-deps
    - name: Run E2e Tests on Kubernetes 1.30
      run: make e2e-1.30